### ISSUE TITLE
win10上，node8.9.4，在yarn的时候，最终会报错

### ISSUE THREAD

**Issue by wmtiger** [brucx/wepy-zanui-demo#12]
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-config-standard@7.1.0" has incorrect peer dependency "eslint-plugin-promise@>=3.3.0".
[4/4] Building fresh packages...
[1/3] ⠈ node-sass: Build failed with error code: 1
[2/3] ⠈ mozjpeg
[3/3] ⠈ pngquant-bin
[-/3] ⠈ waiting...
error E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-sass
Output:
Building: C:\nodejs8\node.exe E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs8\\node.exe',
gyp verb cli   'E:\\development\\wxproj\\wxxcx\\wepy\\wepy-zanui-demo\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\weishaoming\AppData\Local\Programs\Python\Python36\python.EXE
gyp verb check python version `C:\Users\weishaoming\AppData\Local\Programs\Python\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.4\r\n"
gyp verb could not find "C:\Users\weishaoming\AppData\Local\Programs\Python\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Users\weishaoming\AppData\Local\Programs\Python\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\weishaoming\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\nodejs8\\node.exe" "E:\\development\\wxproj\\wxxcx\\wepy\\wepy-zanui-demo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\development\wxproj\wxxcx\wepy\wepy-zanui-demo\node_modules\node-sass
gyp ERR! node -v v8.9.4

这个意思是，要python2吗？我装的大概是3

**Comment by supwjm** [comment]
我也报了相同的错误

**Comment by supwjm** [comment]
发现用yarn安装会报错，用npm就不会，但是编译出来的样式仍然不对

**Comment by kofzhoubiwen** [comment]
MARK 没退路的么
